tickers:
  - AAPL
  - ACLS
  - ACM
  - ACMR
  - AEHR
  - ALAB
  - AMAT
  - AMD
  - AMKR
  - AMZN
  - ANET
  - APH
  - ARM
  - ASML
  - AVGO
  - BE
  - BTDR
  - CAMT
  - CARR
  - CEG
  - CIEN
  - CIFR
  - CLS
  - COHR
  - COHU
  - CORZ
  - CRDO
  - CRM
  - CRWD
  - CRWV
  - CSCO
  - D
  - DDOG
  - DELL
  - ECL
  - ENTG
  - ETN
  - ETR
  - FIX
  - FLEX
  - FLR
  - FN
  - FORM
  - GEV
  - GLW
  - GNRC
  - GOOGL
  - HPE
  - HUBB
  - ICHR
  - IGV
  - INTC
  - IRDM
  - IREN
  - IYW
  - JBL
  - KEYS
  - KLAC
  - KLIC
  - LITE
  - LRCX
  - MCHP
  - MDB
  - META
  - MKSI
  - MOD
  - MPWR
  - MRVL
  - MSFT
  - MU
  - NET
  - NOW
  - NTAP
  - NVDA
  - NVT
  - NXPI
  - ON
  - ORCL
  - PANW
  - PLTR
  - POWL
  - PSTG
  - PWR
  - QCOM
  - QQQ
  - SANM
  - SMCI
  - SMH
  - SNDK
  - SNOW
  - SOXL
  - SOXX
  - SPY
  - STX
  - TER
  - TQQQ
  - TSLA
  - TSM
  - TXN
  - VECO
  - VRT
  - VST
  - WDC
  - XLK
  - ZS
